{{- if index .Values "infra-services" "demo_app_enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ bkst_app_name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: ${{ bkst_app_name }}
    server: https://kubernetes.default.svc
  project: 'applications'
  source:
    helm:
      releaseName: ${{ bkst_app_name }}
      valueFiles:
      - ../applications/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "region" }}/infra-facts.yaml
      - ../${{ bkst_app_name }}/values.yaml
      - ../${{ bkst_app_name }}/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "region" }}/values.yaml
      values: |
        global:
          vars:
            BASE_DB_URL: {{ index .Values "infra-services" "rds_cluster_endpoint" }}
        tokenization-component:
          externalsecretEnv:
            env:
            - name: DATASOURCE_USERNAME
              key: {{ index .Values "infra-services" "rds_master_credentials_secret_name" }}
              property: username
            - name: DATASOURCE_PASSWORD
              key: {{ index .Values "infra-services" "rds_master_credentials_secret_name" }}
              property: password
          ingress:
            annotations:
              external-dns.alpha.kubernetes.io/hostname: tokenization-component.{{ index .Values "infra-services" "environment" }}.{{ index .Values "infra-services" "dns_main_domain" }}.
            dynamic:
              tls: false
              baseDomain: {{ index .Values "infra-services" "dns_main_domain" }}
          
    path: helm/${{ bkst_app_name }}
    repoURL: {{ index .Values "infra-services" "applications_destination_repo" }}
    targetRevision: HEAD
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true
  revisionHistoryLimit: 3
{{- end }}